pub mod agent_drive;
mod agent_drive_apply_tests;
mod agent_drive_approval_tests;
pub mod agent_drive_approvals;
pub mod agent_drive_bridge;
mod agent_drive_steps;
mod agent_drive_tests;
pub mod agent_drive_types;
pub mod agent_executor;
mod agent_executor_apply_tests;
pub mod agent_executor_bridge;
mod agent_executor_bridge_tests;
mod agent_executor_tests;
pub mod agent_patch_apply_step;
mod agent_patch_apply_step_tests;
pub mod agent_patch_draft_bridge;
mod agent_patch_draft_bridge_tests;
pub mod agent_patch_draft_context;
mod agent_patch_draft_context_tests;
pub mod agent_patch_draft_dispatch;
mod agent_patch_draft_parser;
mod agent_patch_draft_receipts;
pub mod agent_patch_draft_step;
mod agent_patch_draft_step_tests;
pub mod agent_patch_restore_executor;
mod agent_patch_restore_executor_tests;
pub mod agent_review_executor;
pub mod agent_review_executor_bridge;
mod agent_review_executor_bridge_tests;
mod agent_review_executor_tests;
pub mod agent_review_revision_bridge;
mod agent_review_revision_bridge_tests;
pub mod agent_review_step;
mod agent_review_step_tests;
pub mod agent_run;
pub mod agent_run_commands;
mod agent_run_evidence_persistence;
mod agent_run_ids;
mod agent_run_outcome;
pub mod agent_run_persistence;
mod agent_run_tests;
mod agent_run_types;
pub mod agent_scheduler;
mod agent_scheduler_apply_tests;
mod agent_scheduler_approvals;
pub mod agent_scheduler_bridge;
mod agent_scheduler_bridge_apply_tests;
mod agent_scheduler_bridge_tests;
mod agent_scheduler_bridge_view;
mod agent_scheduler_patch_context;
mod agent_scheduler_patch_context_tests;
mod agent_scheduler_repair_tests;
mod agent_scheduler_test_context;
mod agent_scheduler_test_context_tests;
mod agent_scheduler_tests;
pub mod agent_test_executor;
pub mod agent_test_executor_bridge;
mod agent_test_executor_bridge_tests;
mod agent_test_executor_tests;
pub mod agent_test_step;
mod agent_test_step_tests;
pub mod agent_tool_loop;
pub mod agent_tools;
mod agent_tools_tests;
pub mod approval;
pub mod approval_bridge;
mod approval_bridge_keys;
pub mod approval_bridge_taxonomy;
mod approval_bridge_tests;
pub mod approval_persistence;
mod approval_persistence_tests;
mod approval_policy;
mod approval_tests;
mod approval_types;
pub mod attachment;
pub mod attachment_bridge;
pub mod attachment_bridge_ops;
pub mod attachment_bridge_types;
pub mod attachment_diagnostics;
mod attachment_diagnostics_tests;
pub mod attachment_evidence;
mod attachment_evidence_tests;
pub mod attachment_external;
mod attachment_external_tests;
pub mod attachment_kind;
pub mod attachment_media;
mod attachment_media_tests;
pub mod attachment_parser;
mod attachment_parser_tests;
pub mod attachment_persistence;
mod attachment_persistence_tests;
pub mod attachment_policy;
pub mod attachment_record_persistence;
mod attachment_tests;
pub mod automation;
pub mod automation_bridge;
mod automation_bridge_tests;
mod automation_bridge_views;
pub mod automation_persistence;
mod automation_persistence_tests;
mod automation_tests;
pub mod campaign;
pub mod campaign_bridge;
mod campaign_bridge_more_tests;
mod campaign_bridge_prompts;
mod campaign_bridge_records;
mod campaign_bridge_requests;
mod campaign_bridge_tests;
mod campaign_bridge_views;
pub mod campaign_delta;
mod campaign_delta_tests;
pub mod campaign_dice;
mod campaign_dice_tests;
pub mod campaign_model;
pub mod campaign_packs;
mod campaign_packs_tests;
pub mod campaign_packs_user;
mod campaign_packs_user_tests;
pub mod campaign_persistence;
pub mod campaign_persistence_codec;
mod campaign_persistence_tests;
pub mod campaign_prompt;
mod campaign_prompt_tests;
pub mod campaign_store_ops;
mod campaign_tests;
pub mod cli_chat;
mod cli_chat_tests;
pub mod cli_review;
mod cli_review_tests;
pub mod command_exec;
mod command_exec_tests;
pub mod context_pack;
mod context_pack_tests;
mod d1_shared_store_tests;
pub mod desktop_shell;
pub mod explore_plan;
mod explore_plan_tests;
pub mod external_agent;
mod external_agent_adapters;
pub mod external_agent_command_contracts;
mod external_agent_command_contracts_tests;
pub mod external_agent_contract_bridge;
mod external_agent_contract_bridge_tests;
mod external_agent_diff;
mod external_agent_guard_tests;
mod external_agent_isolation;
mod external_agent_patch_promotion;
mod external_agent_patch_promotion_tests;
pub mod external_agent_run_bridge;
mod external_agent_run_bridge_claude_tests;
mod external_agent_run_bridge_keys;
mod external_agent_run_bridge_tests;
mod external_agent_run_bridge_types;
pub mod external_agent_run_persistence;
mod external_agent_run_persistence_tests;
mod external_agent_scope;
pub mod external_agent_status_bridge;
mod external_agent_status_bridge_tests;
pub mod external_agent_stream_json;
mod external_agent_stream_json_tests;
pub mod external_agent_terminal;
mod external_agent_terminal_tests;
mod external_agent_tests;
mod external_agent_types;
pub mod local_store_bridge;
mod local_store_bridge_tests;
pub mod memory;
pub mod memory_bridge;
mod memory_bridge_tests;
mod memory_bridge_views;
pub mod memory_persistence;
mod memory_persistence_tests;
mod memory_tests;
pub mod mobile;
mod mobile_tests;
pub mod model_chat;
mod model_chat_tests;
pub mod model_embedded;
pub mod model_embedded_bridge;
mod model_embedded_engine;
pub mod model_embedded_persistence;
mod model_embedded_persistence_tests;
mod model_ollama;
mod model_ollama_http;
mod model_ollama_tests;
mod model_ollama_version;
mod model_ollama_version_tests;
pub mod model_provider;
pub mod model_provider_persistence;
mod model_provider_persistence_tests;
mod model_provider_tests;
pub mod ollama_models;
mod ollama_models_tests;
pub mod patch;
mod patch_apply_bridge;
mod patch_apply_bridge_tests;
pub mod patch_bridge;
mod patch_bridge_tests;
mod patch_diff;
mod patch_intent_tests;
pub mod patch_persistence;
mod patch_persistence_tests;
mod patch_restore_bridge;
mod patch_restore_bridge_tests;
mod patch_tests;
pub mod plan_bridge;
pub mod plan_persistence;
mod plan_persistence_tests;
pub mod project;
pub mod project_bridge;
pub mod project_persistence;
mod project_persistence_tests;
mod project_tests;
pub mod release;
pub mod release_bridge;
mod release_bridge_requests;
mod release_bridge_tests;
pub mod release_bridge_views;
pub mod release_file_export_persistence;
pub mod release_persistence;
mod release_persistence_tests;
mod release_support_export;
mod release_support_export_tests;
mod release_tests;
pub mod research;
pub mod research_persistence;
mod research_persistence_tests;
mod research_tests;
pub mod review;
pub mod review_bridge;
mod review_bridge_keys;
mod review_bridge_tests;
mod review_helpers;
pub mod review_persistence;
mod review_persistence_tests;
mod review_tests;
pub mod runtime_bridge;
mod runtime_bridge_tests;
pub mod sandbox_capability;
mod sandbox_capability_tests;
pub mod secret_bridge;
mod secret_bridge_tests;
pub mod secret_store;
pub mod skills;
pub mod skills_bridge;
mod skills_bridge_tests;
pub mod skills_persistence;
mod skills_persistence_tests;
mod skills_tests;
pub mod sqlite_store;
mod sqlite_store_tests;
pub mod terminal_command_prep;
mod terminal_command_prep_tests;
pub mod test_runner;
pub mod test_runner_bridge;
mod test_runner_bridge_tests;
pub mod test_runner_persistence;
mod test_runner_persistence_tests;
mod test_runner_tests;
pub mod thread_run_bridge;
mod thread_run_bridge_parse;
mod thread_run_bridge_state;
mod thread_run_bridge_tests;
pub mod thread_run_bridge_views;
pub mod thread_run_final_answer;
mod thread_run_final_answer_tests;
pub(crate) mod thread_run_final_support;
pub mod thread_run_persistence;
mod thread_run_persistence_tests;
pub mod threads;
mod threads_tests;
pub mod workbench_modes;
mod workbench_modes_tests;
pub mod workspace;
pub mod workspace_bridge;
mod workspace_bridge_tests;
mod workspace_git;
mod workspace_git_tests;
pub mod workspace_persistence;
mod workspace_persistence_tests;
mod workspace_tests;

pub use desktop_shell::{desktop_shell_info, DesktopShellInfo, APP_IDENTIFIER, APP_NAME};
