import type { AgentRunStatus, AgentRunView } from "../features/runs/agentRunTypes";
import type { TaskThread } from "../features/threads/threadTypes";

export function recordModelCallStarted(
  runs: AgentRunView[],
  thread: TaskThread,
  modelId: string,
  createdAt: string,
) {
  if (!thread.activeRunId) {
    return runs;
  }
  return runs.map((run) => (
    run.id === thread.activeRunId ? runWithModelCallStarted(run, modelId, createdAt) : run
  ));
}

export function recordModelCallResult(
  runs: AgentRunView[],
  thread: TaskThread,
  providerId: string,
  modelId: string,
  responseText: string,
  createdAt: string,
  nextStatus: AgentRunStatus = "succeeded",
) {
  if (!thread.activeRunId) {
    return runs;
  }
  return runs.map((run) => (
    run.id === thread.activeRunId ? runWithModelCallResult(run, providerId, modelId, responseText, createdAt, nextStatus) : run
  ));
}

export function recordModelCallFailure(
  runs: AgentRunView[],
  thread: TaskThread,
  modelId: string,
  error: string,
  createdAt: string,
  nextStatus: AgentRunStatus = "failed",
) {
  if (!thread.activeRunId) {
    return runs;
  }
  return runs.map((run) => (
    run.id === thread.activeRunId ? runWithModelCallFailure(run, modelId, error, createdAt, nextStatus) : run
  ));
}

function runWithModelCallStarted(run: AgentRunView, modelId: string, createdAt: string): AgentRunView {
  const nodeId = `${run.id}-model-call-${modelCallIndex(run)}`;
  const events = [...run.events, modelEvent(run, nodeId, "model_call.started", `Ollama request sent to ${modelId}.`, { modelId }, createdAt)];
  return {
    ...run,
    events,
    metrics: { ...run.metrics, eventCount: events.length },
    status: "running",
    updatedAt: createdAt,
  };
}

function runWithModelCallResult(
  run: AgentRunView,
  providerId: string,
  modelId: string,
  responseText: string,
  createdAt: string,
  nextStatus: AgentRunStatus,
): AgentRunView {
  const nodeId = `${run.id}-model-call-${modelCallIndex(run)}`;
  const artifactId = `${nodeId}-artifact`;
  const evidenceId = `${nodeId}-evidence`;
  const events = [...run.events, modelEvent(run, nodeId, "model_call.completed", `Ollama replied with ${modelId}.`, { artifactId, modelId, providerId }, createdAt)];
  return {
    ...run,
    artifacts: [...run.artifacts, { createdAt, id: artifactId, kind: "model_response", metadata: { modelId, providerId }, runId: run.id, title: `Ollama response from ${modelId}` }],
    evidence: [...run.evidence, { id: evidenceId, relevance: { reason: "Model output was generated by this local model call.", relationship: "unknown", score: 1 }, retrievedAt: createdAt, runId: run.id, sourceId: artifactId, sourceKind: "model_call", title: `Model call: ${modelId}` }],
    events,
    metrics: { ...run.metrics, artifactCount: run.artifacts.length + 1, evidenceCount: run.evidence.length + 1, eventCount: events.length, nodeCount: run.nodes.length + 1 },
    nodes: [...run.nodes, { completedAt: createdAt, dependsOn: [], id: nodeId, input: { modelId, providerId }, kind: "model_call", output: { responseLength: responseText.length }, runId: run.id, startedAt: createdAt, status: "succeeded" }],
    status: nextStatus,
    updatedAt: createdAt,
  };
}

function runWithModelCallFailure(
  run: AgentRunView,
  modelId: string,
  error: string,
  createdAt: string,
  nextStatus: AgentRunStatus,
): AgentRunView {
  const nodeId = `${run.id}-model-call-${modelCallIndex(run)}`;
  const artifactId = `${nodeId}-artifact`;
  const evidenceId = `${nodeId}-evidence`;
  const events = [...run.events, modelEvent(run, nodeId, "model_call.failed", error, { artifactId, modelId }, createdAt)];
  return {
    ...run,
    artifacts: [...run.artifacts, { createdAt, id: artifactId, kind: "model_error", metadata: { error, modelId }, runId: run.id, title: `Ollama failure for ${modelId}` }],
    evidence: [...run.evidence, { id: evidenceId, relevance: { reason: "Failure was captured from this local model call.", relationship: "unknown", score: 1 }, retrievedAt: createdAt, runId: run.id, sourceId: artifactId, sourceKind: "model_call", title: `Failed model call: ${modelId}` }],
    events,
    metrics: { ...run.metrics, artifactCount: run.artifacts.length + 1, evidenceCount: run.evidence.length + 1, eventCount: events.length, nodeCount: run.nodes.length + 1 },
    nodes: [...run.nodes, { completedAt: createdAt, dependsOn: [], error, id: nodeId, input: { modelId }, kind: "model_call", runId: run.id, startedAt: createdAt, status: "failed" }],
    status: nextStatus,
    updatedAt: createdAt,
  };
}

function modelEvent(run: AgentRunView, nodeId: string, kind: string, message: string, payload: unknown, createdAt: string) {
  return {
    createdAt,
    id: `${run.id}-event-${run.events.length + 1}`,
    kind,
    message,
    nodeId,
    payload,
    runId: run.id,
  };
}

function modelCallIndex(run: AgentRunView) {
  return run.nodes.filter((node) => node.kind === "model_call").length + 1;
}
